### ISSUE TITLE
Why there are a backslash on global constant UPLOAD_ERR_OK

### ISSUE THREAD

**Issue by eusonlito** [php-fig/http-factory#3]
On this code:

https://github.com/php-fig/http-factory/blob/378bfe27931ecc54ff824a20d6f6bfc303bbd04c/src/UploadedFileFactoryInterface.php#L30

Why the global constant `UPLOAD_ERR_OK` has a backslash?

Constant is always available on all scopes, including namespaces.

You are using a backslash as convention?

Thanks!

**Comment by Nyholm** [comment]
This is a super small performance boost. 
Instead of letting the engine search for the constant in ALL namespaces, we tell it to just look in the global namespace. 

Im not sure if this is the **only** reason though...

**Comment by WyriHaximus** [comment]
Other reason could be that you can't monkey patch a value into that constant by declaring `Psr\Http\Message\UPLOAD_ERR_OK` somewhere else.

**Comment by eusonlito** [comment]
@WyriHaximus but about these idea, you will need to escape all built-in functions http://php.net/manual/en/language.namespaces.fallback.php

**Comment by eusonlito** [comment]
@Nyholm, it's a nano performance boost :stuck_out_tongue: 

Engine will search constant in current namespace and in global context as fallback, not in ALL namespaces, no?

**Comment by WyriHaximus** [comment]
@eusonlito Correct, and that can have a performance boost. [We had a PR with it on the ReactPHP event loop giving us a ~10% performance gain.](https://github.com/reactphp/event-loop/pull/167) And IIRC there is something to make this mandatory, could be an RFC not sure

**Comment by shadowhand** [comment]
Rather than performance, I would look at it in terms of semantics. Writing constants this way (for very public code) clearly states: This is a global constant. No one is going to go looking for where *we* defined `UPLOAD_ERR_OK` by mistake.

**Comment by eusonlito** [comment]
Understood :)
