### ISSUE TITLE
Why are these interfaces released targeting only php 7 and above

### ISSUE THREAD

**Issue by drnkwati** [php-fig/http-factory#5]
Hi
My deep concerns concerning these interfaces is that developers are tied to latest php builds
I see type hinting not supported in old php versions
why is this?

**Comment by Nyholm** [comment]
They are targeted to the php versions that are supported. Currently, php7.1 and php7.2 are the active supported versions. But you can use these interfaces even with 7.0. 

Read more at http://php.net/supported-versions.php

**Comment by shadowhand** [comment]
The reasons for using PHP 7+ is also outlined [in the meta document](https://www.php-fig.org/psr/psr-17/meta/#51-why-php-7).

**Comment by drnkwati** [comment]
Yes guys i understand. But the reality show is most servers still run even old PHP 5.4.
Big companies like Godaddy still run 5.4 yep. Its a shame and i left them.

**Comment by stefanotorresi** [comment]
Forgive me if I sound rude, but you're beating on a dead horse: we already discussed this, took a decision, reviewed and approved the documents. This ship has sailed, get over it.

**Comment by drnkwati** [comment]
No offense man.
I appreciate and respect the work you guys are doing and i move on already.
Don't get me wrong either because I am not encouraging or promoting outdated php versions.

Stefano Torresi you have to work on your communication skills. You were rude and asked me to forgive you. I forgive you. It wasn't necessary to make this statement "This ship has sailed, get over it"

All the same guys keep up the good work.

**Comment by stefanotorresi** [comment]
I didn't mean to be rude, man, it's just that this kind of discussion keeps popping up so I couldn't help expressing a bit of annoyance.
Anyway, thanks for your interest and appreciation.
